import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#F3F0EE",
        lifted: "#FCFBFA",
        paper: "#FAF9F6",
        white: "#FFFFFF",
        ink: "#141413",
        charcoal: "#262627",
        slate: "#696969",
        "warm-muted": "#8C8C8C",
        granite: "#555555",
        dust: "#D1CDC7",
        signal: "#CF4500",
        "light-signal": "#F37338",
        clay: "#9A3A0A",
        "link-blue": "#3860BE",
        ghost: "#E8E2DA",
        hairline: "#E8E5E0",
        callout: "#F5F3EF",
        bg: "#F3F0EE",
        dim: "#696969",
        faint: "#D1CDC7",
        line: "#141413",
        accent: "#CF4500",
      },
      fontFamily: {
        sans: ["var(--font-sofia-sans)", "Arial", "sans-serif"],
        display: ["var(--font-playfair)", "Noto Serif SC", "serif"],
        serif: ["var(--font-lora)", "Noto Serif SC", "serif"],
      },
      borderRadius: {
        pill: "999px",
        stadium: "40px",
        button: "20px",
      },
      boxShadow: {
        nav: "rgba(0, 0, 0, 0.04) 0px 4px 24px 0px",
        card: "rgba(0, 0, 0, 0.08) 0px 24px 48px 0px",
        drama: "rgba(0, 0, 0, 0.25) 0px 70px 110px 0px",
      },
      typography: {
        DEFAULT: {
          css: {
            color: "rgba(0, 0, 0, 0.84)",
            fontSize: "21px",
            lineHeight: "1.58",
            letterSpacing: "-0.03px",
            maxWidth: "none",
            fontFamily: "var(--font-lora), 'Noto Serif SC', serif",
            textRendering: "optimizeLegibility",
            a: {
              color: "rgba(0, 0, 0, 0.84)",
              textDecoration: "underline",
              fontWeight: "400",
            },
            "a:hover": {
              color: "rgba(0, 0, 0, 0.84)",
            },
            h2: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              fontSize: "26px",
              fontWeight: "700",
              lineHeight: "34.5px",
              color: "rgba(0, 0, 0, 0.84)",
              letterSpacing: "-0.45px",
              marginTop: "56px",
              marginBottom: "-13px",
              marginLeft: "-1.883px",
              padding: "0",
              borderTop: "none",
              borderBottom: "none",
            },
            h3: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              fontSize: "22px",
              fontWeight: "700",
              lineHeight: "1.3",
              color: "rgba(0, 0, 0, 0.84)",
              letterSpacing: "-0.3px",
              marginTop: "48px",
              marginBottom: "-10px",
            },
            h4: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              fontSize: "19px",
              fontWeight: "700",
              color: "rgba(0, 0, 0, 0.84)",
              marginTop: "40px",
              marginBottom: "-8px",
            },
            h5: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              fontSize: "17px",
              fontWeight: "700",
              color: "rgba(0, 0, 0, 0.84)",
              marginTop: "32px",
              marginBottom: "-6px",
            },
            h6: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              fontSize: "15px",
              fontWeight: "700",
              color: "rgba(0, 0, 0, 0.54)",
              marginTop: "28px",
              marginBottom: "-6px",
            },
            p: {
              marginTop: "21px",
              marginBottom: "0",
            },
            blockquote: {
              fontFamily: "var(--font-playfair), 'Noto Serif SC', serif",
              fontSize: "30px",
              fontStyle: "italic",
              letterSpacing: "-0.36px",
              lineHeight: "44.4px",
              color: "rgba(0, 0, 0, 0.68)",
              borderLeft: "none",
              background: "transparent",
              padding: "0 0 0 50px",
              marginTop: "55px",
              marginBottom: "33px",
              fontWeight: "400",
            },
            "blockquote p": {
              marginTop: "0",
              marginBottom: "0",
              color: "rgba(0, 0, 0, 0.68)",
              fontFamily: "inherit",
              fontSize: "inherit",
              lineHeight: "inherit",
              fontStyle: "italic",
            },
            "blockquote a": {
              color: "rgba(0, 0, 0, 0.68)",
            },
            code: {
              fontSize: "18px",
              backgroundColor: "rgba(0,0,0,0.05)",
              borderRadius: "2px",
              padding: "3px 5px",
              fontWeight: "400",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: {
              backgroundColor: "rgba(0,0,0,0.05)",
              border: "none",
              borderRadius: "2px",
              padding: "20px",
              overflowX: "auto",
              marginTop: "21px",
              marginBottom: "21px",
            },
            "pre code": {
              backgroundColor: "transparent",
              border: "none",
              padding: "0",
              fontSize: "18px",
              lineHeight: "1.58",
              color: "rgba(0, 0, 0, 0.84)",
            },
            img: {
              borderRadius: "0",
              marginTop: "0",
              marginBottom: "0",
              marginLeft: "auto",
              marginRight: "auto",
              display: "block",
            },
            figure: {
              marginTop: "55px",
              marginBottom: "33px",
              marginLeft: "0",
              marginRight: "0",
            },
            figcaption: {
              fontFamily: "var(--font-lato), Arial, sans-serif",
              color: "rgba(0, 0, 0, 0.54)",
              fontSize: "14px",
              textAlign: "center",
              marginTop: "12px",
              fontStyle: "normal",
              lineHeight: "1.4",
            },
            ul: {
              marginTop: "21px",
              marginBottom: "0",
              paddingLeft: "1.5em",
            },
            ol: {
              marginTop: "21px",
              marginBottom: "0",
              paddingLeft: "1.5em",
            },
            li: {
              marginTop: "0.4em",
              marginBottom: "0.4em",
            },
            "ul li::marker": {
              color: "rgba(0, 0, 0, 0.54)",
            },
            hr: {
              border: "none",
              marginTop: "55px",
              marginBottom: "55px",
              textAlign: "center",
            },
            "h2:first-child": { marginTop: "0" },
            "h3:first-child": { marginTop: "0" },
            "h4:first-child": { marginTop: "0" },
            "p:first-child": { marginTop: "0" },
            "figure:first-child": { marginTop: "0" },
          },
        },
      },
    },
  },
  plugins: [typography],
};

export default config;
